const ALERT = 'ALERT';
const REFETCH_CHAT = 'REFETCH_CHAT';
const NEW_ATTACHMENTS = 'NEW_ATTACHMENTS';
const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT';
const NEW_REQUEST = 'NEW_REQUEST';
const NEW_MESSAGE = 'NEW_MESSAGE';
const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const ONLINE_USERS = "ONLINE_USERS";
const OFFLINE_USERS = "OFFLINE_USERS";
const CONNECT_USERS = "CONNECT_USERS";

export {
    ALERT,
    REFETCH_CHAT,
    NEW_ATTACHMENTS,
    NEW_MESSAGE_ALERT,
    NEW_REQUEST,
    NEW_MESSAGE,
    RECEIVE_MESSAGE,
    START_TYPING,
    STOP_TYPING,
    ONLINE_USERS,
    OFFLINE_USERS,
    CONNECT_USERS
}